name: Build Stats Page from CloudFront logs
on:
  schedule:
    - cron: "0 0 * * 3" # Every Wednesday at midnight
jobs:
  build-stats-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli build-essential libgeoip-dev libncursesw5-dev \
            libtokyocabinet-dev libssl-dev zlib1g-dev wget
      - name: Install GoAccess 1.9.1
        run: |
          wget https://tar.goaccess.io/goaccess-1.9.1.tar.gz
          tar -xzvf goaccess-1.9.1.tar.gz
          cd goaccess-1.9.1/
          ./configure --enable-utf8 --enable-geoip=legacy
          make
          sudo make install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync CloudFront logs
        run: |
          aws s3 sync s3://logs-cloudfront-chrisdempewolf.com ./cloudfront-logs/ --size-only
      - name: Build aggregate log file
        run: |
          batch_size=4096
          files=()
          for file in cloudfront-logs/*.gz; do
            # echo "Processing $file"
            file_size=$(stat -c%s "$file")
            if [ $file_size -eq 0 ]; then
              echo "Skipping empty file: $file"
              continue
            fi
            files+=("$file")
            if [ ${#files[@]} -eq $batch_size ]; then
              echo "Processing batch of ${#files[@]} files"
              for f in "${files[@]}"; do
                zcat "$f" >> goaccess.log
              done
              files=()
            fi
          done
          # Process remaining files in the last batch
          if [ ${#files[@]} -ne 0 ]; then
            echo "Processing final batch of ${#files[@]} files"
            for f in "${files[@]}"; do
              zcat "$f" >> goaccess.log
            done
          fi
      - name: Process aggregate log file
        run: |
          goaccess goaccess.log -o ./public/stats.html --log-format CLOUDFRONT --time-format CLOUDFRONT --date-format CLOUDFRONT
      - name: Commit and push changes
        run: |
          git config --global user.email "github@green-world.uk"
          git config --global user.name "Github Actions"
          git checkout main
          git add cloudfront-logs/ public/stats.html
          git commit -m "Update CloudFront logs and stats"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}