name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.8'
          extensions: mbstring, intl, bcmath
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Laravel migrations and seeders
        run: |
          php artisan migrate:fresh
          php artisan db:seed

      - name: Start Laravel server
        run: php artisan serve --host=0.0.0.0 --port=8000 &

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./output s3://chrisdempewolf.com --color on --exclude "*.woff2" --exclude "*.otf" --delete
          aws cloudfront create-invalidation --distribution-id E22OYIS6W2FQMI --paths /*
        shell: bash

